#!/usr/bin/env php
<?php

require_once __DIR__.'/vendor/autoload.php';

$app = require __DIR__.'/src/init.php';
require __DIR__.'/config/prod.php';
require __DIR__.'/src/app.php';
$console = require __DIR__.'/src/console.php';
$console->run();
